[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist" # change to "build" if that's your output folder (default for Create React App)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200