[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-npm-install"

  [plugins.inputs]
  npm_version = "9.8.1"
  install_flags = ["--legacy-peer-deps"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
